//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcEjemplo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int cod_producto { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public string descripcion { get; set; }
        public string marca { get; set; }
        public Nullable<decimal> precio_unitario { get; set; }
        public Nullable<System.DateTime> fec_vencimiento { get; set; }
    }
}
